import { auth } from "~/server/auth";
import { api, HydrateClient } from "~/trpc/server";
import { signIn, signOut } from "next-auth/react";
import Head from "next/head";

import { Header } from "./_components/Header";
import { Content } from "./_components/Content";

export default async function Home() {
  const session = await auth();

  if (session?.user) {
    void api.post.getLatest.prefetch();
    void api.topic.getAll.prefetch();
  }

  return (
    <HydrateClient>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header signIn={signIn} signOut={signOut} sessionData={session} />
        <Content sessionData={session} />
      </main>
    </HydrateClient>
  );
}