import { auth } from "~/server/auth";
import { api, HydrateClient } from "~/trpc/server";
import Head from "next/head";

import { Header } from "./_components/Header";

export default async function Home() {
  const session = await auth();

  if (session?.user) {
    void api.post.getLatest.prefetch();
  }

  return (
    <HydrateClient>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header sessionData={session} />
      </main>
    </HydrateClient>
  );
}
